### ISSUE TITLE
Livewire 3 without NPM Building?

### ISSUE THREAD

**Issue by WorthLMS** [hans-lts/alpine-validation#1]
Is there a way to get this to work without having to use NPM?

Since Alpine is already provided in L3?

**Comment by hans-lts** [comment]
I will look into this, I feel like it shouldn't be overly complicated

**Comment by hans-lts** [comment]
@WorthLMS I updated the package so it should be working via CDN now. Would you mind confirming on your project?

You can just drop this in:
```html
<script src="https://cdn.jsdelivr.net/npm/wire-validation@latest/dist/wire-validation.min.js"></script>
```

**Comment by WorthLMS** [comment]
Thank you I can check it on Monday. Nuch appreciated

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Hans Link ***@***.***>
Sent: Friday, August 9, 2024 5:38:09 PM
To: hans-lts/alpine-validation ***@***.***>
Cc: Software ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]:Re: [hans-lts/alpine-validation] Livewire 3 without NPM Building? (Issue #1)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@WorthLMS<https://github.com/WorthLMS> I updated the package so it should be working via CDN now. Would you mind confirming on your project?

You can just drop this in:

<script ***@***.***/dist/wire-validation.min.js"></script>

**Comment by hans-lts** [comment]
@WorthLMS Any luck? I'll close this issue but feel free to comment here if there's still a problem.
